site_name: Docs

nav:
  - Home: index.md
  - Description: ReadMe.md

dev_addr: 127.0.0.1:8001

theme: readthedocs

markdown_extensions:
  - toc:
      permalink: "#"

use_directory_urls: False
docs_dir: docs
site_dir: site