# Generated by Django 5.0.1 on 2024-01-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='Автор', max_length=30, verbose_name='Автор')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='Введите заголовок', max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(default='Введите техт', help_text='Содержание статьи', verbose_name='Содержание')),
            ],
        ),
    ]
