# Generated by Django 5.0.1 on 2024-02-24 14:52

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Никнейм', max_length=100)),
                ('user', models.OneToOneField(help_text='Автор', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='Введите заголовок', max_length=50, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Содержание статьи', verbose_name='Содержание')),
                ('category', models.CharField(choices=[('Танки', 'Танки'), ('Хилы', 'Хилы'), ('ДД', 'ДД'), ('Торговцы', 'Торговцы'), ('Гилдмастеры', 'Гилдмастеры'), ('Квестгиверы', 'Квестгиверы'), ('Кузнецы', 'Кузнецы'), ('Кожевники', 'Кожевники'), ('Зельевары', 'Зельевары'), ('Мастера заклинаний', 'Мастера заклинаний')], help_text='Введите категорию', max_length=20, verbose_name='Категория')),
                ('video', models.FileField(blank=True, null=True, upload_to=main.models.Post.user_directory_path, verbose_name='video')),
                ('audio', models.FileField(blank=True, null=True, upload_to=main.models.Post.user_directory_path, verbose_name='audio')),
                ('image', models.ImageField(blank=True, upload_to=main.models.Post.user_directory_path, verbose_name='image')),
                ('enable_comments', models.BooleanField(default=True)),
                ('author', models.ForeignKey(help_text='Автор', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
