# Generated by Django 5.0.1 on 2024-01-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
